language: objective-c
xcode_project: PreviewSlider.xcodeproj # path to your xcodeproj folder
xcode_scheme: PreviewSlider
#script:
#- xcodebuild -project PreviewSlider.xcodeproj -scheme PreviewSlider -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test